#!/usr/bin/env python3
"""Pulse EQ — a small GTK front end for PipeWire's built-in parametric EQ."""

import json
import math
import os
import shutil
import subprocess
import sys
from pathlib import Path

import gi
gi.require_version("Gtk", "4.0")
gi.require_version("Adw", "1")
from gi.repository import Adw, Gtk, Gio, GLib, Gdk
import cairo  # Registers PyGObject's Cairo argument converters for custom drawing.

APP_ID = "io.github.pulseeq.PulseEQ"
FREQUENCIES = [31, 63, 125, 250, 500, 1000, 2000, 4000, 8000, 16000]
LABELS = ["31", "63", "125", "250", "500", "1k", "2k", "4k", "8k", "16k"]
STATE_DIR = Path(GLib.get_user_config_dir()) / "pulse-eq"
STATE_FILE = STATE_DIR / "state.json"
PIPEWIRE_FILE = Path(GLib.get_user_config_dir()) / "pipewire" / "pipewire.conf.d" / "90-pulse-eq.conf"

PRESETS = {
    "Flat": [0] * 10,
    "Bass boost": [5, 4, 3, 1, 0, 0, 0, 0, 0, 0],
    "Vocal": [-2, -1, 0, 1, 3, 3, 2, 1, 0, 0],
    "Treble": [0, 0, 0, 0, 0, 0, 1, 2, 4, 5],
    "Warm": [3, 2, 1, 0, -1, 0, 1, 1, 0, -1],
}

CSS = """
window { background: #101112; color: #e9e9e7; }
.shell { background: #101112; }
.topbar { padding: 18px 28px 14px; }
.brand { font-size: 16px; font-weight: 700; letter-spacing: .2px; }
.subtitle { color: #868984; font-size: 12px; }
.content { padding: 14px 28px 24px; }
.hero { font-size: 34px; font-weight: 650; letter-spacing: -1.2px; }
.muted { color: #8c908a; }
.panel { background: #171918; border: 1px solid #252927; border-radius: 18px; padding: 20px; }
.band-card { background: #141615; border: 1px solid #252927; border-radius: 14px; padding: 12px 5px; }
.band-label { color: #a9aea8; font-size: 11px; font-weight: 600; }
.band-value { color: #777d76; font-size: 10px; }
scale trough { background: #303530; border-radius: 99px; min-width: 4px; }
scale highlight { background: #bdff69; border-radius: 99px; }
scale slider { background: #d5ff9c; border: 2px solid #101112; min-width: 15px; min-height: 15px; }
button.preset { background: #202321; border: 1px solid #2c302d; border-radius: 10px; color: #c5c9c2; padding: 8px 13px; }
button.preset:checked { background: #293420; border-color: #718d4c; color: #d9ffad; }
button.apply { background: #c7ff78; color: #1b2112; border-radius: 11px; font-weight: 700; padding: 11px 18px; }
button.apply:hover { background: #d7ff9e; }
button.flat { color: #aeb2ac; }
.status { background: #171918; border: 1px solid #252927; border-radius: 12px; padding: 12px 15px; }
.status-dot { color: #bfff70; }
.separator { background: #252927; }
.hint { color: #787e77; font-size: 11px; }
"""


def load_state():
    try:
        data = json.loads(STATE_FILE.read_text())
        values = data.get("bands", [0] * 10)
        return [max(-12.0, min(12.0, float(v))) for v in values[:10]] + [0.0] * max(0, 10-len(values)), data.get("preset", "Flat")
    except (OSError, ValueError, TypeError):
        return [0.0] * 10, "Flat"


def pipewire_config(values):
    filters = "\n".join(
        f'                    {{ type = bq_peaking, freq = {freq}, gain = {gain:.1f}, q = 1.4 }}'
        for freq, gain in zip(FREQUENCIES, values)
    )
    return f'''# Generated by Pulse EQ. Edit this file through the app.
context.modules = [
  {{ name = libpipewire-module-filter-chain
    args = {{
      node.description = "Pulse EQ"
      media.name = "Pulse EQ"
      filter.graph = {{
        nodes = [ {{ type = builtin, name = eq, label = param_eq,
          config = {{ filters = [
{filters}
          ] }} }} ]
      }}
      capture.props = {{ node.name = "pulse_eq_input", media.class = "Audio/Sink", audio.position = [ FL FR ] }}
      playback.props = {{ node.name = "pulse_eq_output", node.passive = true, audio.position = [ FL FR ], target.object = "@DEFAULT_AUDIO_SINK@" }}
    }}
  }}
]
'''


class Curve(Gtk.DrawingArea):
    def __init__(self, get_values):
        super().__init__(content_height=120, hexpand=True)
        self.get_values = get_values
        self.set_draw_func(self.draw)

    def draw(self, area, cr, width, height):
        cr.set_line_width(1)
        cr.set_source_rgba(.72, .77, .70, .12)
        for y in [height * .15, height * .5, height * .85]:
            cr.move_to(0, y); cr.line_to(width, y); cr.stroke()
        vals = self.get_values()
        pts = []
        for i, val in enumerate(vals):
            x = 14 + i * (width - 28) / 9
            y = height / 2 - (val / 12) * (height * .40)
            pts.append((x, y))
        cr.set_source_rgba(.75, 1, .42, .12)
        cr.move_to(pts[0][0], height)
        for x, y in pts: cr.line_to(x, y)
        cr.line_to(pts[-1][0], height); cr.close_path(); cr.fill()
        cr.set_source_rgb(.76, 1, .44); cr.set_line_width(2.5)
        cr.move_to(*pts[0])
        for i in range(1, len(pts)):
            x0, y0 = pts[i-1]; x1, y1 = pts[i]
            dx = (x1-x0)/3
            cr.curve_to(x0+dx, y0, x1-dx, y1, x1, y1)
        cr.stroke()
        for x, y in pts:
            cr.arc(x, y, 3, 0, math.tau); cr.set_source_rgb(.82, 1, .60); cr.fill()


class PulseEQ(Adw.Application):
    def __init__(self):
        super().__init__(application_id=APP_ID, flags=Gio.ApplicationFlags.DEFAULT_FLAGS)
        self.values, self.preset_name = load_state()
        self.sliders = []
        self.connect("activate", self.activate)

    def activate(self, *_):
        if hasattr(self, "window"):
            self.window.present(); return
        Adw.StyleManager.get_default().set_color_scheme(Adw.ColorScheme.FORCE_DARK)
        display = Gdk.Display.get_default()
        provider = Gtk.CssProvider(); provider.load_from_data(CSS.encode())
        Gtk.StyleContext.add_provider_for_display(display, provider, Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION)
        self.window = Adw.ApplicationWindow(application=self, title="Pulse EQ", default_width=900, default_height=720)
        root = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, css_classes=["shell"])
        self.window.set_content(root)
        root.append(self.header())
        root.append(Gtk.Separator(css_classes=["separator"]))
        scroll = Gtk.ScrolledWindow(vexpand=True, hscrollbar_policy=Gtk.PolicyType.NEVER)
        root.append(scroll)
        body = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=20, css_classes=["content"])
        body.set_halign(Gtk.Align.CENTER); body.set_size_request(680, -1)
        scroll.set_child(body)
        intro = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=4)
        intro.append(Gtk.Label(label="Shape your sound.", xalign=0, css_classes=["hero"]))
        intro.append(Gtk.Label(label="A precise, featherweight equalizer for PipeWire.", xalign=0, css_classes=["muted"]))
        body.append(intro)
        self.status = Gtk.Label(xalign=0, css_classes=["status"])
        body.append(self.status); self.refresh_status()
        card = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=10, css_classes=["panel"])
        body.append(card)
        self.curve = Curve(lambda: [s.get_value() for s in self.sliders])
        card.append(self.curve)
        row = Gtk.Box(spacing=8, homogeneous=True, valign=Gtk.Align.FILL)
        card.append(row)
        for i, (freq, label) in enumerate(zip(FREQUENCIES, LABELS)):
            col = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=7, halign=Gtk.Align.CENTER, css_classes=["band-card"])
            col.append(Gtk.Label(label=f"{freq} Hz" if freq < 1000 else f"{freq//1000} kHz", css_classes=["band-label"]))
            scale = Gtk.Scale.new_with_range(Gtk.Orientation.VERTICAL, -12, 12, .5)
            scale.set_inverted(True); scale.set_draw_value(False); scale.set_size_request(30, 168)
            scale.set_value(self.values[i]); scale.connect("value-changed", self.changed, i)
            col.append(scale); row.append(col); self.sliders.append(scale)
            self.value_labels = getattr(self, "value_labels", [])
            value_label = Gtk.Label(label=f"{self.values[i]:+.1f}", css_classes=["band-value"])
            col.append(value_label); self.value_labels.append(value_label)
        presets = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=10, css_classes=["panel"])
        body.append(presets)
        preset_head = Gtk.Box()
        preset_head.append(Gtk.Label(label="QUICK START", xalign=0, hexpand=True, css_classes=["band-label"]))
        self.preset_hint = Gtk.Label(label=self.preset_name, css_classes=["hint"])
        preset_head.append(self.preset_hint); presets.append(preset_head)
        pills = Gtk.Box(spacing=8)
        presets.append(pills)
        self.preset_buttons = {}
        for name in PRESETS:
            b = Gtk.ToggleButton(label=name, css_classes=["preset"])
            b.connect("toggled", self.choose_preset, name)
            pills.append(b); self.preset_buttons[name] = b
        self.update_preset_button()
        footer = Gtk.Box(spacing=12, valign=Gtk.Align.CENTER)
        body.append(footer)
        apply = Gtk.Button(label="Apply to PipeWire  ↗", css_classes=["apply"])
        apply.connect("clicked", self.apply_config); footer.append(apply)
        reset = Gtk.Button(label="Reset", css_classes=["flat"])
        reset.connect("clicked", self.reset); footer.append(reset)
        footer.append(Gtk.Label(label="Applies system-wide after a brief audio restart.", hexpand=True, xalign=1, css_classes=["hint"]))
        self.window.present()

    def header(self):
        bar = Gtk.Box(spacing=11, valign=Gtk.Align.CENTER, css_classes=["topbar"])
        mark = Gtk.DrawingArea(content_width=26, content_height=26)
        mark.set_draw_func(self.draw_mark); bar.append(mark)
        texts = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=1)
        texts.append(Gtk.Label(label="pulse eq", xalign=0, css_classes=["brand"]))
        texts.append(Gtk.Label(label="PIPEWIRE AUDIO", xalign=0, css_classes=["subtitle"]))
        bar.append(texts)
        bar.append(Gtk.Label(label="10 BAND  ·  BUILT FOR LINUX", hexpand=True, xalign=1, css_classes=["subtitle"]))
        return bar

    @staticmethod
    def draw_mark(area, cr, width, height):
        cr.set_source_rgb(.76, 1, .44); cr.set_line_width(2.5); cr.set_line_cap(1)
        coords = [(2,16),(7,16),(10,7),(14,21),(18,11),(21,16),(25,16)]
        cr.move_to(*coords[0])
        for p in coords[1:]: cr.line_to(*p)
        cr.stroke()

    def changed(self, slider, idx):
        self.values[idx] = slider.get_value()
        self.value_labels[idx].set_text(f"{self.values[idx]:+.1f}")
        self.preset_name = "Custom"; self.preset_hint.set_text("Custom")
        self.update_preset_button(); self.curve.queue_draw(); self.save_state()

    def choose_preset(self, button, name):
        if button.get_active():
            self.preset_name = name
            for i, value in enumerate(PRESETS[name]): self.sliders[i].set_value(value)
            self.preset_hint.set_text(name); self.update_preset_button(); self.save_state()

    def update_preset_button(self):
        if not hasattr(self, "preset_buttons"): return
        for name, button in self.preset_buttons.items():
            button.handler_block_by_func(self.choose_preset)
            button.set_active(name == self.preset_name)
            button.handler_unblock_by_func(self.choose_preset)

    def reset(self, *_):
        self.preset_name = "Flat"
        for slider in self.sliders: slider.set_value(0)
        self.preset_hint.set_text("Flat"); self.update_preset_button(); self.save_state()

    def save_state(self):
        STATE_DIR.mkdir(parents=True, exist_ok=True)
        STATE_FILE.write_text(json.dumps({"bands": self.values, "preset": self.preset_name}, indent=2))

    def refresh_status(self):
        active = PIPEWIRE_FILE.exists()
        self.status.set_text(("●  Equalizer configured   ·   Apply changes to update audio" if active else "●  PipeWire ready   ·   Apply to install the equalizer") if shutil.which("pw-cli") else "●  PipeWire tools not found")

    def apply_config(self, *_):
        if not shutil.which("pw-cli"):
            self.notify("PipeWire command line tools are missing."); return
        try:
            PIPEWIRE_FILE.parent.mkdir(parents=True, exist_ok=True)
            PIPEWIRE_FILE.write_text(pipewire_config([s.get_value() for s in self.sliders]))
            self.save_state()
            services = ["pipewire.service", "wireplumber.service"]
            if subprocess.run(["systemctl", "--user", "is-active", "--quiet", "pipewire-pulse.service"]).returncode == 0:
                services.append("pipewire-pulse.service")
            result = subprocess.run(["systemctl", "--user", "restart", *services], capture_output=True, text=True, timeout=20)
            if result.returncode:
                self.notify("Config saved. Restart PipeWire from a terminal to activate it.")
            else:
                self.notify("Equalizer applied. Select ‘Pulse EQ’ as your output in audio settings.")
            self.refresh_status()
        except (OSError, subprocess.TimeoutExpired) as exc:
            self.notify(f"Couldn't apply equalizer: {exc}")

    def notify(self, message):
        dialog = Adw.AlertDialog(heading="Pulse EQ", body=message)
        dialog.add_response("ok", "OK")
        dialog.present(self.window)


if __name__ == "__main__":
    app = PulseEQ()
    raise SystemExit(app.run(sys.argv))
